services:
  tyumenctf2025_redirects:
    build: .
    ports:
      - "5000:5000"
    deploy:
      resources:
        requests:
          cpus: '0.25'
          memory: 128M
        limits:
          cpus: '0.5'
          memory: 256M