services:
  tyumenctf2025_laboratory:
    build: .
    ports:
      - "5010:5010"
    deploy:
      resources:
        requests:
          cpus: '0.25'
          memory: 128M
        limits:
          cpus: '0.5'
          memory: 256M