services:
  cryptoanalysis:
    build: .
    ports:
      - "5011:5000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4096M
        reservations:
          cpus: '0.5'
          memory: 2048M
